api/urls.py
from django.urls import path, include

from rest_framework import routers

from api.views import PostViewSet, CategoryViewSet

router = routers.DefaultRouter()
# router.register(r'posts', PostViewSet)
router.register(r'categories', CategoryViewSet)
# router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('posts/<int:pk>/', PostViewSet.as_view(), name='posts'),
    # path('categories/', CategoryViewSet.as_view(), name='category'),
    path('api-auth/',
         include('rest_framework.urls', namespace='rest_framework'))
]

blog/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from blog.views import redirect_blog
from posts.views import login_view


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('', redirect_blog, name='index'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('login/', login_view),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += [
   url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

posts/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/',
         cache_page(60, cache='db_cache')(views.PostDetailView.as_view()),
         name='details'),
    path('add_post/', views.PostCreateView.as_view(), name='add_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post')
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.auth.models import User, AbstractUser
from django.utils.functional import cached_property

from tags.models import TaggedItem


class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(status=Post.STATUS_PUBLISHED)


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def published(self):
        return self.get_queryset().published()


class Post(models.Model):
    STATUS_DRAFT = 'D'
    STATUS_PUBLISHED = 'P'
    STATUS_REJECTED = 'R'
    STATUS = (
        (STATUS_DRAFT, 'Draft'),
        (STATUS_PUBLISHED, 'Published'),
        (STATUS_REJECTED, 'Rejected'),
    )
    objects = PostManager()

    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    categories = models.ManyToManyField(
        'Category',
        through='PostCategory'
    )
    status = models.CharField(
        choices=STATUS,
        default=STATUS_DRAFT,
        max_length=100
    )
    tags = GenericRelation(TaggedItem)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse("posts:details", args=[self.pk])

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    @cached_property
    def get_tags_list(self):
        return [t.tag.name for t in self.tags.all().order_by('-tag__name')]


class Category(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class PostCategory(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='post_categories'
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE
    )
    is_main = models.BooleanField(default=False)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    text = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)

# class Author(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='author')
#     posts = models.ManyToManyField(Post)


# class AuthorAbs(AbstractUser):
#     posts = models.ManyToManyField(Post)

posts/forms.py
from django import forms
from django.forms import ValidationError

from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'status']

    # title = forms.CharField(
    #     label='Title',
    #     min_length=2,
    #     # max_length=100,
    # )
    # content = forms.CharField(
    #     widget=forms.Textarea,
    #     max_length=1000
    # )
    #

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            raise ValidationError('validation error!')
        return title


class LoginForm(forms.Form):
    username = forms.CharField(max_length=128)
    password = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput
    )


class RegisterForm(LoginForm):
    confirm_password = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput
    )

    def clean(self):
        password = self.cleaned_data['password']
        confirm = self.cleaned_data['confirm_password']

        if password != confirm:
            raise forms.ValidationError('Password not equal')

        return self.cleaned_data

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.core.cache import caches, cache

from django.utils.translation import gettext as _

from .models import Post
from .forms import PostForm, LoginForm


class PostListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post
    template_name = 'post/index.html'
    context_object_name = 'posts'

    login_url = '/login/'
    permission_required = ['can_view_posts']

    def get_queryset(self):
        print(self.request.user)
        print(self.request.user.is_authenticated)
        # return Post.objects.prefetch_related(
        #     'post_categories__category'
        # )
        return Post.objects.published()


class PostDetailView(DetailView):
    model = Post
    template_name = 'post/details.html'
    context_object_name = 'post'


class PostCreateView(CreateView):
    # model = Post
    template_name = 'post/add_post.html'
    form_class = PostForm
    # context_object_name = 'post'
    # fields = ['title', 'content']


class MyView(View):
    def get(self, request, *args, **kwargs):
        form = PostForm()
        return render(request, 'post/add_post.html', context={'form': form})

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)
        if form.is_valid():
            p = Post(
                title=form.cleaned_data['title'],
                content=form.cleaned_data['content']
            )
            p.save()
            return redirect('posts:index')
        return render(request, 'post/add_post.html', context={'form': form})


@login_required(login_url='/login/')
@cache_page(60, cache='db_cache')
def index(request):
    db_cache = caches['db_cache']
    posts = db_cache.get('posts_list', [])
    if not posts:
        posts = Post.objects.all()
        db_cache.set('posts_list', list(posts), 240)
        print('!!!cached')

    posts_title = _('Posts')

    context = {
        'posts': posts,
        'title': posts_title
    }
    # request.session['user_id'] = 111
    # request.session['user_data'] = {
    #     'posts': 32
    # }
    # del request.session['user_id']
    #
    # request.session['user_data']['posts'] = 22
    # request.session.modified = True
    #
    # request.session.set_expiry(0)  # время жизни сессии
    # request.session.flush()  # удалить текущую сессию
    #
    # from django.contrib.auth.models import User
    #
    # user = User.objects.create_user('username', 'email@email.com', 'password')
    # user.set_password('new_password')
    # user.save()

    return render(request, 'post/index.html', context)


def post_details(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm()
    context = {'post': post, 'form': form}
    return render(request, 'post/details.html', context)


def add_post(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            p = Post(
                title=form.cleaned_data['title'],
                content=form.cleaned_data['content']
            )
            p.save()
            return redirect('posts:index')
    return render(request, 'post/add_post.html', context={'form': form})


def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(initial={'title': post.title, 'content': post.content, 'status': post.status})
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = request.POST['title']
            post.content = request.POST['content']
            post.save()
            return redirect('posts:index')
    context = {'post': post, 'form': form}
    return render(request, 'post/edit_post.html', context)


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(
                                username=form.cleaned_data['username'],
                                password=form.cleaned_data['password']
            )
            if user.is_active:
                login(request, user)
                return redirect('/posts')
        return render(request, 'post/login.html', {'form': form})
    else:
        form = LoginForm()

    return render(request, 'post/login.html', {'form': form})


def logout_view(request):
    logout(request)

    return redirect('/login/')


def register_view(request):
    User.objects.get(username='admin').check_password('admin')

posts/templates/post/add_post.html
{% extends 'post/base.html' %}
{% load cache %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% cache 120 form %}
        {{form.as_p}}
    {% endcache %}
    {{form.errors}}
    <button class="btn btn-primary btn-lg btn-block">Add post</button>
</form>
{% endblock %}

posts/templates/post/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Django Blog · Python</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <!-- Favicons -->
    <meta name="theme-color" content="#7952b3">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      .blog-footer {
        padding: 1.5rem 0;
        color: #727272;
        text-align: center;
        background-color: #f9f9f9;
        border-top: .05rem solid #e5e5e5;
}

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


    </style>

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">

</head>
<body>

<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-6 pt-1">
                <a class="link-secondary" href="{% url 'posts:index' %}">HOMEPAGE</a>
            </div>
            <div class="col-6 d-flex justify-content-end align-items-center">
                <a class="link-secondary" href="#" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                         stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img"
                         viewBox="0 0 24 24"><title>Search</title>
                        <circle cx="10.5" cy="10.5" r="7.5"/>
                        <path d="M21 21l-5.2-5.2"/>
                    </svg>
                </a>
                {% if user.is_authenticated %}
                <span>Welcome, <b>{{ user.username }}</b>!</span>
                {% else %}
                <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 link-secondary" href="{% url 'posts:add_post' %}">ADD POST</a>
        </nav>
    </div>
</div>

<main class="container">
    <div class="row g-5">
        <div class="col-md-8">
            {% block content %}{% endblock %}
        </div>

        <div class="col-md-4">
            <div class="position-sticky" style="top: 2rem;">
                <div class="p-4 mb-3 bg-light rounded">
                    <h4 class="fst-italic">About</h4>
                    <p class="mb-0">Customize this section to tell your visitors a little bit about your publication,
                        writers, content, or something else entirely. Totally up to you.</p>
                </div>

                <div class="p-4">
                    <h4 class="fst-italic">Archives</h4>
                    <ol class="list-unstyled mb-0">
                        <li><a href="#">March 2021</a></li>
                        <li><a href="#">February 2021</a></li>
                        <li><a href="#">January 2021</a></li>
                        <li><a href="#">December 2020</a></li>
                        <li><a href="#">November 2020</a></li>
                        <li><a href="#">October 2020</a></li>
                        <li><a href="#">September 2020</a></li>
                        <li><a href="#">August 2020</a></li>
                        <li><a href="#">July 2020</a></li>
                        <li><a href="#">June 2020</a></li>
                        <li><a href="#">May 2020</a></li>
                        <li><a href="#">April 2020</a></li>
                    </ol>
                </div>

                <div class="p-4">
                    <h4 class="fst-italic">Elsewhere</h4>
                    <ol class="list-unstyled">
                        <li><a href="#">GitHub</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

</main>

<footer class="blog-footer">
    <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap.</a>
    </p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

</body>
</html>

posts/templates/post/details.html
{% extends 'post/base.html' %}

{% block content %}
<article class="blog-post">
    <h2 class="blog-post-title">{{post.title}}</h2>
    <p class="blog-post-meta">{{post.created_at}}</p>
    <p>{{post.content}}</p>
    <p><a href="{% url 'posts:edit_post' post.id%}">---> Edit Blog Post</a></p>
</article>
{% endblock %}

posts/templates/post/edit_post.html
{% extends 'post/base.html' %}

{% block content %}
<h1>Edit post</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    {{ form.errors }}
    <button class="btn btn-primary btn-lg btn-block">Update</button>
</form>
{% endblock content %}

posts/templates/post/index.html
{% extends 'post/base.html' %}

{% load i18n %}

{% block content %}
<h1>{% translate 'Posts' %}</h1>
<div>
    {% language 'en' %}
        {% blocktranslate with amount=posts.count %}
            You have {{ amount }} posts.
        {% endblocktranslate %}
    {% endlanguage %}
</div>
{% for post in posts %}

<div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
        <strong class="d-inline-block mb-2 text-primary">
            {% for c in post.categories.all %}
                {{c.name}}
            {% endfor %}
        </strong>
        <h5 class="mb-0 text-muted">{{post.get_status_display}}</h5>
        <h3 class="mb-0">{{post.title}}</h3>
        <div class="mb-1 text-muted">{{post.created_at}}</div>
        <p class="card-text mb-auto">{{post.content}}</p>
        <a href="{% url 'posts:details' post.id%}" class="stretched-link">Continue reading ---></a>
    </div>
    <div class="col-auto d-none d-lg-block">
        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg"
             role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
             focusable="false"><title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect>
            <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
        </svg>
    </div>
</div>

{% endfor %}

{% endblock %}

posts/templates/post/login.html
{% extends 'post/base.html' %}

{% block title %}LOGIN{% endblock %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>
{% endblock %}